// SPDX-License-Identifier: MIT
// !! THIS FILE WAS AUTOGENERATED BY abi-to-sol v0.8.0. SEE SOURCE BELOW. !!
pragma solidity >=0.7.0 <0.9.0;

interface IRadiantGift {

event Approval( address indexed owner,address indexed approved,uint256 indexed tokenId ) ;
event ApprovalForAll( address indexed owner,address indexed operator,bool approved ) ;
event RoleAdminChanged( bytes32 indexed role,bytes32 indexed previousAdminRole,bytes32 indexed newAdminRole ) ;
event RoleGranted( bytes32 indexed role,address indexed account,address indexed sender ) ;
event RoleRevoked( bytes32 indexed role,address indexed account,address indexed sender ) ;
event Transfer( address indexed from,address indexed to,uint256 indexed tokenId ) ;
function DEFAULT_ADMIN_ROLE(  ) external view returns (bytes32 ) ;
function MINTER_ROLE(  ) external view returns (bytes32 ) ;
function PAUSER_ROLE(  ) external view returns (bytes32 ) ;
function approve( address to,uint256 tokenId ) external   ;
function balanceOf( address owner ) external view returns (uint256 ) ;
function burn( uint256 tokenId ) external   ;
function contractURI(  ) external view returns (string memory ) ;
function getApproved( uint256 tokenId ) external view returns (address ) ;
function getRoleAdmin( bytes32 role ) external view returns (bytes32 ) ;
function grantRole( bytes32 role,address account ) external   ;
function hasRole( bytes32 role,address account ) external view returns (bool ) ;
function hashToTokenId( bytes32  ) external view returns (uint256 ) ;
function image(  ) external view returns (string memory ) ;
function isApprovedForAll( address owner,address operator ) external view returns (bool ) ;
function maxSupply(  ) external view returns (uint256 ) ;
function mint( address to,string memory rng ) external   ;
function name(  ) external view returns (string memory ) ;
function ownerOf( uint256 tokenId ) external view returns (address ) ;
function renounceRole( bytes32 role,address account ) external   ;
function revokeRole( bytes32 role,address account ) external   ;
function safeTransferFrom( address from,address to,uint256 tokenId ) external   ;
function safeTransferFrom( address from,address to,uint256 tokenId,bytes memory data ) external   ;
function setApprovalForAll( address operator,bool approved ) external   ;
function setBaseURI( string memory newBaseURI ) external   ;
function setContractURI( string memory newURI ) external   ;
function setMaxSupply( uint256 newMaxSupply ) external   ;
function supportsInterface( bytes4 interfaceId ) external view returns (bool ) ;
function symbol(  ) external view returns (string memory ) ;
function tokenByIndex( uint256 index ) external view returns (uint256 ) ;
function tokenIdToHash( uint256  ) external view returns (bytes32 ) ;
function tokenOfOwnerByIndex( address owner,uint256 index ) external view returns (uint256 ) ;
function tokenURI( uint256 tokenId ) external view returns (string memory ) ;
function totalSupply(  ) external view returns (uint256 ) ;
function transferFrom( address from,address to,uint256 tokenId ) external   ;
}